[package]
name = "peerce-gui"
version = "0.1.0"
description = "Tauri GUI for Peerce utility"
edition = "2021"

[lib]
name = "tauri_nodejs_frontend_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"

